// Layout principal de l'application avec support multilingue
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { Navbar } from "@/components/Navbar";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Layout principal qui gère le support multilingue
// Accepte les paramètres de locale (fr/en) 
export default async function LocaleLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;

  params: { locales: 'fr' | 'en' };
}>) {
  const { locales } = await Promise.resolve(params);
  return (
    <html lang={locales}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-full max-w-[100vw] overflow-x-hidden`}
      >
        <Navbar params={{ locales }} />
        {children}
      </body>
    </html>
  );
}
